### ISSUE TITLE
[FEAT] 병원 UI 구현

### ISSUE THREAD

**Issue by hyerinlee** [GM-4Masters/Hunter#25]
## 💡 Issue
병원 UI를 구현해야 합니다.
- 새로운 병원 팝업 오브젝트(슬라이드&줌 형식)를 생성.
- json 데이터와 연결하여 플레이어 스탯과 현재 플레이어가 가진 특수상태에 해당하는 치료 데이터를 띄워야 합니다. 이때 특수상태 개수에 따라 슬라이드 활성/비활성화 해주어야 하며 재화가 부족하여 일부 치료 불가능할 경우 해당 버튼 상호작용 비활성화 필요.
- 치료 시 변화된 데이터 적용 및 플레이어에 치료 이펙트 띄우기.

## 📝 To-do
- [x] 병원 팝업 오브젝트 생성
- [x] json 데이터 연결(조건에 따라 일부 요소 비활성화)
- [x] 치료 시 데이터 적용, 이펙트
